### ISSUE TITLE
Missing water texture on 3.1.15 [BUG]

### ISSUE THREAD

**Issue by bl1te** [haubna/PhysicsMod#1128]
**Describe the bug**
After updating to 3.1.15 water texture is missing. Particles and underwater shader are there, but you don't see the water itself when viewing from above.

**To Reproduce**
Install Physics Mod v3.1.15 and approach water.
Look at it.

**Screenshots**
Below

Minecraft Version: Java 1.21.10 (NeoForge 43-beta)
Physics Mod Version: 3.1.15

**Comment by haubna** [comment]
Do you have any other mod installed?

**Comment by haubna** [comment]
I have uploaded 3.1.16 which should fix that issue, could you let me know if that works for you?

**Comment by bl1te** [comment]
Here are some screenshots from a game instance with only your mod installed (no other mod or resource pack):

- 3.1.14: https://i.imgur.com/2ojZJDP.png
- 3.1.15: https://i.imgur.com/brfXAEu.png
- 3.1.16: https://i.imgur.com/I5QsB8F.png

3.1.16 seems to indeed fix the issue, BUT...
In another instance, where Sodium 0.7.2 is installed, the issue is present in both 3.1.15 and 3.1.16.
With Sodium and Physics Mod 3.1.14, however, everything is fine.

**Comment by haubna** [comment]
I wasn't able to reproduce the bug with the latest Sodium version for NeoForge. Are you sure you used Physics Mod 3.1.16 in that test as well?

**Comment by bl1te** [comment]
Just redownloaded both Sodium 0.7.2 and Physics Mod 3.1.16 from CurseForge to be double-sure.
Made another new instance of MC Java 1.21.10 NeoForge 43-beta.
Put both downloaded files there.
The issue persists.

I use SKlauncher 3.2.12 build.558, if it matters.

**Comment by bl1te** [comment]
Hm, on NeoForge 19-beta the bug is absent indeed. Then, I guess, there are some conflicts between **Physics v3.1.15/16** + **Sodium v0.7.2** + **NeoForge v**.. 19 > v <= 43

**Comment by haubna** [comment]
Turns out NeoForge 19 doesn't load Sodium that's why I didn't see the issue. In the end it somehow had a bug with my compiled classes. I uploaded a new 3.1.16 version on modrinth (curseforge will follow). This should fix the issue on the new versions with Sodium.

**Comment by bl1te** [comment]
Can confirm it is fixed now with
New 3.1.16 + Sodium 0.7.2 + NeoForge 43-beta
Thanks
